// <auto-generated />
namespace KryptPadWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_field_sort_order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_field_sort_order));
        
        string IMigrationMetadata.Id
        {
            get { return "201603110331511_update_field_sort_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
