// <auto-generated />
namespace KryptPadWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class item_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(item_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201611091314141_item_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
