// <auto-generated />
namespace KryptPadWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Authorized_Devices1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authorized_Devices1));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031943223_Authorized_Devices1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
